version: '2.2'

services:
    ceph-base:
        image: rhcsdashboard/ceph:${CEPH_IMAGE_TAG:-fedora29}
        domainname: dev
        volumes:
            - ./docker/ceph:/docker:ro
            - ${HOST_CCACHE_DIR}:/root/.ccache
            - ${CEPH_REPO_DIR}:/ceph
            - ${CEPH_CUSTOM_BUILD_DIR:-ceph_build_empty}:/build
        environment:
            - CEPH_ASOK_DIR=/ceph/build/ceph/out
            - CEPH_BIN=/ceph/build/bin
            - CEPH_CONF=/ceph/build/ceph/ceph.conf
            - CEPH_CONF_PATH=/ceph/build/ceph
            - CEPH_DEV_DIR=/ceph/build/ceph/dev
            - CEPH_OUT_DIR=/ceph/build/ceph/out
            - GRAFANA_HOST_PORT=${GRAFANA_HOST_PORT}
            - ALERTMANAGER_HOST_PORT=${ALERTMANAGER_HOST_PORT}
            - MDS
            - MGR
            - MON
            - OSD
            - RGW
        cap_add:
            - ALL
        entrypoint: /docker/entrypoint.sh
        command: /docker/start.sh

    ceph-rpm-base:
        image: ${CEPH_RPM_IMAGE:-rhcsdashboard/nautilus:v14.2.0}
        domainname: dev
        volumes:
            - ./docker/ceph:/docker:ro
            - ${CEPH_RPM_REPO_DIR:-ceph_build_empty}:/ceph/dev
        environment:
            - CEPH_ASOK_DIR=/ceph/dev/build/ceph-rpm/out
            - CEPH_BIN=/usr/bin
            - CEPH_CONF=/ceph/dev/build/ceph-rpm/ceph.conf
            - CEPH_CONF_PATH=/ceph/dev/build/ceph-rpm
            - CEPH_DEV_DIR=/ceph/dev/build/ceph-rpm/dev
            - CEPH_OUT_DIR=/ceph/dev/build/ceph-rpm/out
            - CEPH_RPM_DEV=${CEPH_RPM_DEV:-false}
            - CEPH_RPM_DEV_DIR=/ceph/dev
            - GRAFANA_HOST_PORT=${GRAFANA_HOST_PORT}
            - ALERTMANAGER_HOST_PORT=${ALERTMANAGER_HOST_PORT}
        entrypoint: /docker/rpm/entrypoint.sh
        command: /docker/rpm/start-ceph.sh
        scale: -1
