version: '2.2'

services:
    ceph-base:
        image: rhcsdashboard/ceph:${CEPH_IMAGE_TAG:-fedora29}
        domainname: dev
        volumes:
            - ./docker/ceph:/docker:ro
            - ${HOST_CCACHE_DIR}:/root/.ccache
            - ${CEPH_REPO_DIR}:/ceph
            - ${CEPH_CUSTOM_BUILD_DIR:-ceph_build_empty}:/build
        environment:
            - GRAFANA_HOST_PORT=${GRAFANA_HOST_PORT}
            - ALERTMANAGER_HOST_PORT=${ALERTMANAGER_HOST_PORT}
            - MDS
            - MGR
            - MON
            - OSD
            - RGW
        cap_add:
            - ALL
        entrypoint: /docker/entrypoint.sh
        command: /docker/start.sh

    ceph-rpm-base:
        domainname: dev
        volumes:
            - ./docker/ceph:/docker:ro
            - ${CEPH_REPO_DIR}:/ceph/dev
        environment:
            - CEPH_RPM_DEV=${CEPH_RPM_DEV:-false}
            - GRAFANA_HOST_PORT=${GRAFANA_HOST_PORT}
            - ALERTMANAGER_HOST_PORT=${ALERTMANAGER_HOST_PORT}
        command: /docker/rpm/start-ceph.sh
        scale: -1
