version: '2.2'

services:
    ceph:
        extends:
            file: docker-compose.templates.yml
            service: ceph-base
        container_name: ceph
        hostname: ceph
        networks:
            default:
                aliases:
                    - 'ceph.dev'
        ports: ['${CEPH_PROXY_HOST_PORT:-4200}:4200','${CEPH_HOST_PORT:-11000}:11000']

    ceph-host2:
        extends:
            file: docker-compose.templates.yml
            service: ceph-base
        container_name: ceph-host2
        hostname: ceph-host2
        command: /docker/start-ceph-additional-host.sh
        scale: -1

    ceph2:
        extends:
            file: docker-compose.templates.yml
            service: ceph-base
        image: rhcsdashboard/ceph:${CEPH2_IMAGE_TAG:-fedora29}
        container_name: ceph2
        hostname: ceph2
        networks:
            default:
                aliases:
                    - 'ceph2.dev'
        ports: ['${CEPH2_PROXY_HOST_PORT:-4202}:4200','${CEPH2_HOST_PORT:-11002}:11000']
        volumes:
            - ${CEPH2_REPO_DIR}:/ceph
            - ${CEPH2_CUSTOM_BUILD_DIR:-ceph_build_empty}:/build
        environment:
            - CEPH_ASOK_DIR=/ceph/build/ceph2/out
            - CEPH_CONF=/ceph/build/ceph2/ceph.conf
            - CEPH_CONF_PATH=/ceph/build/ceph2
            - CEPH_DEV_DIR=/ceph/build/ceph2/dev
            - CEPH_OUT_DIR=/ceph/build/ceph2/out
        scale: -1

    ceph-rpm:
        extends:
            file: docker-compose.templates.yml
            service: ceph-rpm-base
        container_name: ceph-rpm
        hostname: ceph-rpm
        networks:
            default:
                aliases:
                    - 'ceph-rpm.dev'
        ports: ['${CEPH_RPM_HOST_PORT:-11001}:11000']

    ceph-rpm-host2:
        extends:
            file: docker-compose.templates.yml
            service: ceph-rpm-base
        container_name: ceph-rpm-host2
        hostname: ceph-rpm-host2
        command: /docker/start-ceph-additional-host.sh
        scale: -1

    grafana:
        image: rhcsdashboard/grafana
        container_name: grafana
        hostname: grafana
        domainname: dev
        networks:
            default:
                aliases:
                    - 'grafana.dev'
        ports: ['${GRAFANA_HOST_PORT:-3000}:3000']
        volumes:
            - grafana_data:/var/lib/grafana
            - ./docker/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
            - ./docker/grafana/provisioning:/etc/grafana/provisioning
            - ${CEPH_REPO_DIR}/monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards/ceph:ro

    prometheus:
        image: prom/prometheus:v2.5.0
        container_name: prometheus
        hostname: prometheus
        domainname: dev
        networks:
            default:
                aliases:
                    - 'prometheus.dev'
        ports: ['${PROMETHEUS_HOST_PORT:-9090}:9090']
        volumes:
            - ./docker/prometheus:/etc/prometheus:ro

    node-exporter:
        image: prom/node-exporter:v0.17.0
        container_name: node-exporter
        hostname: node-exporter
        domainname: dev
        networks:
            default:
                aliases:
                    - 'node-exporter.dev'
        ports: ['${NODE_EXPORTER_HOST_PORT:-9100}:9100']
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
        command:
            - '--path.procfs=/host/proc'
            - '--path.sysfs=/host/sys'
            - '--no-collector.timex'

    alertmanager:
        image: prom/alertmanager:v0.16.0
        container_name: alertmanager
        hostname: alertmanager
        domainname: dev
        networks:
            default:
                aliases:
                    - 'alertmanager.dev'
        ports: ['${ALERTMANAGER_HOST_PORT:-9093}:9093']
        volumes:
            - ./docker/alertmanager:/etc/alertmanager:ro
        command:
            - '--config.file=/etc/alertmanager/config.yml'

    keycloak:
        image: jboss/keycloak:4.8.3.Final
        container_name: keycloak
        hostname: keycloak
        domainname: dev
        networks:
            default:
                aliases:
                    - 'keycloak.dev'
        ports: ['${KEYCLOAK_HOST_PORT:-8080}:8080']
        volumes:
            - ./docker/keycloak:/docker:ro
        environment:
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=keycloak
        command: -b 0.0.0.0 -Dkeycloak.import=/docker/saml-demo-realm.json
        scale: -1

volumes:
    ceph_build_empty:
    grafana_data:

networks:
    default:
        driver: bridge
        enable_ipv6: true
        ipam:
            driver: default
            config:
                - subnet: 172.20.0.0/24
                - subnet: 2600:3c02:e000:0058::/64
