version: '2.2'

services:
    ceph:
        extends:
            file: docker-compose-base.yml
            service: ceph-base
        container_name: ceph
        hostname: ceph
        networks:
            default:
                aliases:
                    - 'ceph.dev'
        ports: ['${CEPH_PROXY_HOST_PORT:-4200}:4200','${CEPH_HOST_PORT:-11000}:11000']
        volumes:
            - ${CEPH_REPO_DIR}:/ceph
            - ${CEPH_BUILD_DIR:-ceph_build_empty}:/build

    ceph2:
        extends:
            file: docker-compose-base.yml
            service: ceph-base
        container_name: ceph2
        hostname: ceph2
        networks:
            default:
                aliases:
                    - 'ceph2.dev'
        ports: ['${CEPH2_PROXY_HOST_PORT:-4202}:4200','${CEPH2_HOST_PORT:-11002}:11000']
        volumes:
            - ${CEPH2_REPO_DIR}:/ceph
            - ${CEPH2_BUILD_DIR:-ceph_build_empty}:/build
        scale: -1

    rhcs3.2:
        image: rhcsdashboard/rhcs3.2
        container_name: rhcs3.2
        hostname: rhcs3-2
        domainname: dev
        networks:
            default:
                aliases:
                    - 'rhcs3-2.dev'
        ports: ['${RHCS3_2_HOST_PORT:-11032}:11000']
        volumes:
            - ./docker/ceph:/docker:ro
            - ${CEPH_REPO_DIR}:/ceph/debug
        environment:
            - GRAFANA_HOSTNAME=${HOSTNAME}
            - GRAFANA_HOST_PORT=${GRAFANA_HOST_PORT}
        command: /docker/rhcs/3.2/start.sh
        scale: -1

    luminous:
        image: rhcsdashboard/luminous
        container_name: luminous
        hostname: luminous
        domainname: dev
        networks:
            default:
                aliases:
                    - 'luminous.dev'
        ports: ['${LUMINOUS_HOST_PORT:-11012}:11000']
        volumes:
            - ./docker/ceph:/docker:ro
            - ${CEPH_REPO_DIR}:/ceph/debug
        environment:
            - GRAFANA_HOST_PORT=${GRAFANA_HOST_PORT}
        command: /docker/luminous/start.sh
        scale: -1

    prometheus:
        image: 'quay.io/prometheus/prometheus'
        container_name: prometheus
        hostname: prometheus
        domainname: dev
        networks:
            default:
                aliases:
                    - 'prometheus.dev'
        ports: ['${PROMETHEUS_HOST_PORT:-9090}:9090']
        volumes:
            - ./docker/prometheus:/etc/prometheus:ro

    grafana:
        image: rhcsdashboard/grafana
        container_name: grafana
        hostname: grafana
        domainname: dev
        networks:
            default:
                aliases:
                    - 'grafana.dev'
        ports: ['${GRAFANA_HOST_PORT:-3000}:3000']
        volumes:
            - grafana_data:/var/lib/grafana
            - ./docker/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
            - ./docker/grafana/provisioning:/etc/grafana/provisioning
            - ${CEPH_REPO_DIR}/monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards/ceph:ro
        depends_on:
            - prometheus

volumes:
    ceph_build_empty:
    grafana_data:

networks:
    default:
        driver: bridge
        enable_ipv6: true
        ipam:
            driver: default
            config:
                - subnet: 172.20.0.0/24
                - subnet: 2600:3c02:e000:0058::/64
