global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus.dev:9090']
  - job_name: 'ceph'
    static_configs:
      - targets: ['ceph.dev:9283']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter.dev:9100']
