name: Publish ceph images

on:
  push:
    branches: 
      - master
    paths:
    - .github/workflows/main.yml
    - docker/ceph/aws/aws-cli-configure.sh
    - docker/ceph/centos/Dockerfile
    - docker/ceph/master/Dockerfile
    - docker/ceph/nautilus/Dockerfile
    - docker/ceph/octopus/Dockerfile
    - docker/ceph/rpm/master/Dockerfile
    - docker/ceph/rpm/nautilus/Dockerfile
    - docker/ceph/rpm/octopus/Dockerfile
    - docker/ceph/rpm/set-ceph-repo.sh
  pull_request:
    branches:
      - master
    paths:
    - .github/workflows/main.yml
    - docker/ceph/aws/aws-cli-configure.sh
    - docker/ceph/centos/Dockerfile
    - docker/ceph/master/Dockerfile
    - docker/ceph/nautilus/Dockerfile
    - docker/ceph/octopus/Dockerfile
    - docker/ceph/rpm/master/Dockerfile
    - docker/ceph/rpm/nautilus/Dockerfile
    - docker/ceph/rpm/octopus/Dockerfile
    - docker/ceph/rpm/set-ceph-repo.sh
  schedule:
    - cron:  '0 2 * * *'

jobs:
  build-ceph-base:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [centos8]
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build
      run: docker build -t docker.io/rhcsdashboard/ceph-base:${{ matrix.os }} -f docker/ceph/centos/Dockerfile ./docker/ceph
    - name: Google Chat Notification
      uses: Co-qn/google-chat-notification@b9227d9daa4638c9782a5bd16c4abb86268127a1
      with:
        name: Build
        url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
        status: ${{ job.status }}
      if: failure()      
    - name: Push
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push docker.io/rhcsdashboard/ceph-base:${{ matrix.os }}
        docker logout
  build-ceph:
    needs: build-ceph-base
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        branch: [master, pacific, octopus, nautilus]
        name: [ceph, ceph-rpm]
        include:
          - name: ceph
            dir: ceph
          - name: ceph-rpm
            dir: ceph/rpm
          - branch: nautilus
            branch_dir: nautilus
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build
      run: docker build -t docker.io/rhcsdashboard/${{ matrix.name }}:${{ matrix.branch }} -f docker/${{ matrix.dir }}/${{ matrix.branch_dir}}/Dockerfile ./docker/ceph --build-arg CEPH_RELEASE=${{ matrix.branch }} --build-arg VCS_BRANCH=${{ matrix.branch }}
    - name: Google Chat Notification
      uses: Co-qn/google-chat-notification@b9227d9daa4638c9782a5bd16c4abb86268127a1
      with:
        name: Build
        url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
        status: ${{ job.status }}
      if: failure()
    - name: Push
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push docker.io/rhcsdashboard/${{ matrix.name }}:${{ matrix.branch }}
        docker logout
